// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBI32sfbV8PgpgSLYcnS19eNUtl4_kHvrE',
    appId: '1:35622543215:android:fed6af94b8bc84a68c529a',
    messagingSenderId: '35622543215',
    projectId: 'crypto-handbook-163007',
    databaseURL: 'https://crypto-handbook-163007.firebaseio.com',
    storageBucket: 'crypto-handbook-163007.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIrkuh6m0h7g3bHb9R5J26HMzBcQlHWqc',
    appId: '1:35622543215:ios:79a4c20369eb2f058c529a',
    messagingSenderId: '35622543215',
    projectId: 'crypto-handbook-163007',
    databaseURL: 'https://crypto-handbook-163007.firebaseio.com',
    storageBucket: 'crypto-handbook-163007.appspot.com',
    iosClientId: '35622543215-i0pm7l0ta0ictkhs8bcploucli0l3uk2.apps.googleusercontent.com',
    iosBundleId: 'com.dicoding.ditonton',
  );
}
