// Mocks generated by Mockito 5.2.0 from annotations
// in ditonton/test/presentation/pages/movie_episodes_page_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i6;
import 'dart:ui' as _i7;

import 'package:ditonton/common/state_enum.dart' as _i5;
import 'package:ditonton/domain/entities/episode.dart' as _i4;
import 'package:ditonton/domain/usecases/get_season_episodes.dart' as _i2;
import 'package:ditonton/presentation/provider/movie_episodes_notifier.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeGetSeasonEpisodes_0 extends _i1.Fake
    implements _i2.GetSeasonEpisodes {}

/// A class which mocks [MovieEpisodesNotifier].
///
/// See the documentation for Mockito's code generation for more information.
class MockMovieEpisodesNotifier extends _i1.Mock
    implements _i3.MovieEpisodesNotifier {
  MockMovieEpisodesNotifier() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.GetSeasonEpisodes get getSeasonEpisodes =>
      (super.noSuchMethod(Invocation.getter(#getSeasonEpisodes),
          returnValue: _FakeGetSeasonEpisodes_0()) as _i2.GetSeasonEpisodes);
  @override
  List<_i4.Episode> get seasonEpisodes =>
      (super.noSuchMethod(Invocation.getter(#seasonEpisodes),
          returnValue: <_i4.Episode>[]) as List<_i4.Episode>);
  @override
  _i5.RequestState get seasonState =>
      (super.noSuchMethod(Invocation.getter(#seasonState),
          returnValue: _i5.RequestState.Empty) as _i5.RequestState);
  @override
  String get message =>
      (super.noSuchMethod(Invocation.getter(#message), returnValue: '')
          as String);
  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);
  @override
  _i6.Future<void> fetchSeasonEpisodes(int? id, int? seasonNumber) => (super
      .noSuchMethod(Invocation.method(#fetchSeasonEpisodes, [id, seasonNumber]),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i6.Future<void>);
  @override
  void addListener(_i7.VoidCallback? listener) =>
      super.noSuchMethod(Invocation.method(#addListener, [listener]),
          returnValueForMissingStub: null);
  @override
  void removeListener(_i7.VoidCallback? listener) =>
      super.noSuchMethod(Invocation.method(#removeListener, [listener]),
          returnValueForMissingStub: null);
  @override
  void dispose() => super.noSuchMethod(Invocation.method(#dispose, []),
      returnValueForMissingStub: null);
  @override
  void notifyListeners() =>
      super.noSuchMethod(Invocation.method(#notifyListeners, []),
          returnValueForMissingStub: null);
}
