// Mocks generated by Mockito 5.2.0 from annotations
// in ditonton/test/presentation/pages/tv_episodes_page_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:bloc/bloc.dart' as _i5;
import 'package:ditonton/domain/usecases/get_season_episodes.dart' as _i2;
import 'package:ditonton/presentation/bloc/tv/episodes/tv_episodes_bloc.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeGetSeasonEpisodes_0 extends _i1.Fake
    implements _i2.GetSeasonEpisodes {}

class _FakeTvEpisodesState_1 extends _i1.Fake implements _i3.TvEpisodesState {}

/// A class which mocks [TvEpisodesBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockTvEpisodesBloc extends _i1.Mock implements _i3.TvEpisodesBloc {
  MockTvEpisodesBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.GetSeasonEpisodes get getSeasonEpisodes =>
      (super.noSuchMethod(Invocation.getter(#getSeasonEpisodes),
          returnValue: _FakeGetSeasonEpisodes_0()) as _i2.GetSeasonEpisodes);
  @override
  _i3.TvEpisodesState get state =>
      (super.noSuchMethod(Invocation.getter(#state),
          returnValue: _FakeTvEpisodesState_1()) as _i3.TvEpisodesState);
  @override
  _i4.Stream<_i3.TvEpisodesState> get stream =>
      (super.noSuchMethod(Invocation.getter(#stream),
              returnValue: Stream<_i3.TvEpisodesState>.empty())
          as _i4.Stream<_i3.TvEpisodesState>);
  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);
  @override
  void add(_i3.TvEpisodesEvent? event) =>
      super.noSuchMethod(Invocation.method(#add, [event]),
          returnValueForMissingStub: null);
  @override
  void onEvent(_i3.TvEpisodesEvent? event) =>
      super.noSuchMethod(Invocation.method(#onEvent, [event]),
          returnValueForMissingStub: null);
  @override
  void emit(_i3.TvEpisodesState? state) =>
      super.noSuchMethod(Invocation.method(#emit, [state]),
          returnValueForMissingStub: null);
  @override
  void on<E extends _i3.TvEpisodesEvent>(
          _i5.EventHandler<E, _i3.TvEpisodesState>? handler,
          {_i5.EventTransformer<E>? transformer}) =>
      super.noSuchMethod(
          Invocation.method(#on, [handler], {#transformer: transformer}),
          returnValueForMissingStub: null);
  @override
  void onTransition(
          _i5.Transition<_i3.TvEpisodesEvent, _i3.TvEpisodesState>?
              transition) =>
      super.noSuchMethod(Invocation.method(#onTransition, [transition]),
          returnValueForMissingStub: null);
  @override
  _i4.Future<void> close() => (super.noSuchMethod(Invocation.method(#close, []),
      returnValue: Future<void>.value(),
      returnValueForMissingStub: Future<void>.value()) as _i4.Future<void>);
  @override
  void onChange(_i5.Change<_i3.TvEpisodesState>? change) =>
      super.noSuchMethod(Invocation.method(#onChange, [change]),
          returnValueForMissingStub: null);
  @override
  void addError(Object? error, [StackTrace? stackTrace]) =>
      super.noSuchMethod(Invocation.method(#addError, [error, stackTrace]),
          returnValueForMissingStub: null);
  @override
  void onError(Object? error, StackTrace? stackTrace) =>
      super.noSuchMethod(Invocation.method(#onError, [error, stackTrace]),
          returnValueForMissingStub: null);
}
